name: Publish to NPM
on: workflow_dispatch

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  setup:
    uses: equinor/dm-models/.github/workflows/_setup.yml@main
    with:
      registry-url: 'https://registry.npmjs.org'
      cache-key: ${{ github.sha }}

  publish:
    name: Publish
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Get files
        id: get-files
        uses: actions/cache@v3
        with:
          path: |
            ./*
            .npm
          key: ${{ github.sha }}
      - id: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Log errors to Slack
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: failure()
